on: push
name: CI Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check device available
        run: xcrun xctrace list devices
      - name: Build and test
        run: |
           - xcodebuild clean test -project amiibo-swift.xcworkspace -scheme amiibo-swift -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

        env:
         destination: ${{ matrix.destination }}
