name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Swift Action
      uses: Didstopia/SwiftAction@v1.0.3
      with:
        swift-action: 'test'
