name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -workspace 'amiibo-swift.xcworkspace' -scheme 'amiibo-swift' -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5'
      - name: Test
        run: |
          xcodebuild clean test -workspace 'amiibo-swift.xcworkspace' -scheme 'amiibo-swift' -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5'
