name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -workspace 'amiibo-swift.xcworkspace' -scheme 'amiibo-swift' -destination 'platform=iOS Simulator,name=iPhone 12,OS=13.2'
    - name: Run tests
      run: xcodebuild test -workspace 'amiibo-swift.xcworkspace' -scheme 'amiibo-swift' -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5'

