on: push
name: CI Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.4,name=iPhone X']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check device available
        run: xcrun xctrace list devices
      - name: Build and test
        run: |
          cd Texstyle
          xcodebuild clean test -project Texstyle.xcodeproj -scheme Texstyle -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env:
         destination: ${{ matrix.destination }}
